/* Generated By:JavaCC: Do not edit this line. PeakassoTokenManager.java */

/** Token Manager. */
public class PeakassoTokenManager implements PeakassoConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x2L) != 0L)
            return 2;
         if ((active0 & 0x7b7da8000L) != 0L)
         {
            jjmatchedKind = 11;
            jjmatchedPos = 0;
            return 12;
         }
         return -1;
      case 1:
         if ((active0 & 0x7b7da8000L) != 0L)
         {
            jjmatchedKind = 11;
            jjmatchedPos = 1;
            return 12;
         }
         return -1;
      case 2:
         if ((active0 & 0x3b7da8000L) != 0L)
         {
            jjmatchedKind = 11;
            jjmatchedPos = 2;
            return 12;
         }
         return -1;
      case 3:
         if ((active0 & 0x3b7da8000L) != 0L)
         {
            jjmatchedKind = 11;
            jjmatchedPos = 3;
            return 12;
         }
         return -1;
      case 4:
         if ((active0 & 0x1b7da8000L) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 4;
            }
            return 12;
         }
         return -1;
      case 5:
         if ((active0 & 0xa2000000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x111d28000L) != 0L)
         {
            jjmatchedKind = 11;
            jjmatchedPos = 5;
            return 12;
         }
         return -1;
      case 6:
         if ((active0 & 0xa2000000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x20000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x111d08000L) != 0L)
         {
            jjmatchedKind = 11;
            jjmatchedPos = 6;
            return 12;
         }
         return -1;
      case 7:
         if ((active0 & 0x110000000L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0xa2000000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x20000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 5;
            }
            return -1;
         }
         return -1;
      case 8:
         if ((active0 & 0x110000000L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0xa2000000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x20000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 5;
            }
            return -1;
         }
         return -1;
      case 9:
         if ((active0 & 0x110000000L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0xa2000000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x20000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 5;
            }
            return -1;
         }
         return -1;
      case 10:
         if ((active0 & 0x110000000L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0xa2000000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x20000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 5;
            }
            return -1;
         }
         return -1;
      case 11:
         if ((active0 & 0x110000000L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x82000000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x20000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 5;
            }
            return -1;
         }
         return -1;
      case 12:
         if ((active0 & 0x110000000L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x2000000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x20000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 5;
            }
            return -1;
         }
         return -1;
      case 13:
         if ((active0 & 0x110000000L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x2000000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x20000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 5;
            }
            return -1;
         }
         return -1;
      case 14:
         if ((active0 & 0x10000000L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x2000000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x20000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 5;
            }
            return -1;
         }
         return -1;
      case 15:
         if ((active0 & 0x2000000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x20000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 5;
            }
            return -1;
         }
         return -1;
      case 16:
         if ((active0 & 0x2000000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x20000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 5;
            }
            return -1;
         }
         return -1;
      case 17:
         if ((active0 & 0x2000000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x20000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 5;
            }
            return -1;
         }
         return -1;
      case 18:
         if ((active0 & 0x2000000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x20000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 5;
            }
            return -1;
         }
         return -1;
      case 19:
         if ((active0 & 0x2000000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 4;
            }
            return -1;
         }
         return -1;
      case 20:
         if ((active0 & 0x2000000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 4;
            }
            return -1;
         }
         return -1;
      case 21:
         if ((active0 & 0x2000000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 4;
            }
            return -1;
         }
         return -1;
      case 22:
         if ((active0 & 0x2000000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 4;
            }
            return -1;
         }
         return -1;
      case 23:
         if ((active0 & 0x2000000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 4;
            }
            return -1;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 32:
         return jjStartNfaWithStates_0(0, 1, 2);
      case 39:
         return jjStopAtPos(0, 30);
      case 40:
         return jjStopAtPos(0, 35);
      case 41:
         return jjStopAtPos(0, 36);
      case 42:
         return jjStopAtPos(0, 7);
      case 43:
         return jjStopAtPos(0, 5);
      case 44:
         return jjStopAtPos(0, 27);
      case 45:
         return jjStopAtPos(0, 6);
      case 47:
         return jjStopAtPos(0, 8);
      case 58:
         return jjStopAtPos(0, 18);
      case 59:
         return jjStopAtPos(0, 16);
      case 61:
         return jjStopAtPos(0, 21);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x6000000L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x1da0000L);
      case 68:
         return jjMoveStringLiteralDfa1_0(0x10000000L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x100000000L);
      case 77:
         return jjMoveStringLiteralDfa1_0(0x200000000L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x80008000L);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x20000000L);
      case 84:
         return jjMoveStringLiteralDfa1_0(0x400000000L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa2_0(active0, 0x80020000L);
      case 69:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000L);
      case 79:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(1, 11, 12);
         return jjMoveStringLiteralDfa2_0(active0, 0x200080000L);
      case 82:
         return jjMoveStringLiteralDfa2_0(active0, 0x16008000L);
      case 88:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000000L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x500000L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x1800000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000L);
      case 72:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000L);
      case 73:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000L);
      case 78:
         return jjMoveStringLiteralDfa3_0(active0, 0x200a0000L);
      case 79:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000L);
      case 85:
         return jjMoveStringLiteralDfa3_0(active0, 0x6000000L);
      case 86:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x500000L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x1800000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(3, 11, 12);
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000L);
      case 71:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000L);
      case 73:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000L);
      case 78:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000L);
      case 83:
         return jjMoveStringLiteralDfa4_0(active0, 0x6080000L);
      case 86:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000L);
      case 87:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x1800000L);
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x500000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000L);
      case 66:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000L);
      case 72:
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 11;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000L);
      case 73:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000L);
      case 82:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000L);
      case 84:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(4, 11, 12);
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000L);
      case 87:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000L);
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x500000L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x1800000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa6_0(active0, 0xa2000000L);
      case 65:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000L);
      case 73:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000L);
      case 78:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000L);
      case 83:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000L);
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x1800000L);
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0x500000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000L);
      case 66:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000L);
      case 67:
         return jjMoveStringLiteralDfa7_0(active0, 0x80000000L);
      case 68:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000L);
      case 71:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000L);
      case 77:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(6, 11, 12);
         break;
      case 84:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000000L);
      case 88:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(6, 11, 12);
         else if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(6, 11, 12);
         break;
      case 89:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(6, 11, 12);
         else if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(6, 11, 12);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa8_0(active0, 0x110000000L);
      case 65:
         return jjMoveStringLiteralDfa8_0(active0, 0x80000000L);
      case 69:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000L);
      case 73:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000L);
      case 82:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa9_0(active0, 0x102000000L);
      case 78:
         return jjMoveStringLiteralDfa9_0(active0, 0x80020000L);
      case 83:
         return jjMoveStringLiteralDfa9_0(active0, 0x10000000L);
      case 85:
         return jjMoveStringLiteralDfa9_0(active0, 0x20000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa10_0(active0, 0x100000000L);
      case 69:
         return jjMoveStringLiteralDfa10_0(active0, 0x10000000L);
      case 73:
         return jjMoveStringLiteralDfa10_0(active0, 0x20000L);
      case 76:
         return jjMoveStringLiteralDfa10_0(active0, 0x2000000L);
      case 83:
         return jjMoveStringLiteralDfa10_0(active0, 0x20000000L);
      case 86:
         return jjMoveStringLiteralDfa10_0(active0, 0x80000000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
static private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa11_0(active0, 0x82000000L);
      case 67:
         return jjMoveStringLiteralDfa11_0(active0, 0x10000000L);
      case 72:
         if ((active0 & 0x20000000L) != 0L)
            return jjStopAtPos(10, 29);
         break;
      case 78:
         return jjMoveStringLiteralDfa11_0(active0, 0x100000000L);
      case 84:
         return jjMoveStringLiteralDfa11_0(active0, 0x20000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
static private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa12_0(active0, 0x20000L);
      case 82:
         return jjMoveStringLiteralDfa12_0(active0, 0x2000000L);
      case 83:
         if ((active0 & 0x80000000L) != 0L)
            return jjStopAtPos(11, 31);
         break;
      case 84:
         return jjMoveStringLiteralDfa12_0(active0, 0x10000000L);
      case 86:
         return jjMoveStringLiteralDfa12_0(active0, 0x100000000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
static private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa13_0(active0, 0x102000000L);
      case 73:
         return jjMoveStringLiteralDfa13_0(active0, 0x10000000L);
      case 83:
         return jjMoveStringLiteralDfa13_0(active0, 0x20000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
static private int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa14_0(active0, 0x20000L);
      case 79:
         return jjMoveStringLiteralDfa14_0(active0, 0x10000000L);
      case 83:
         if ((active0 & 0x100000000L) != 0L)
            return jjStopAtPos(13, 32);
         break;
      case 84:
         return jjMoveStringLiteralDfa14_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
static private int jjMoveStringLiteralDfa14_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0);
      return 14;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa15_0(active0, 0x20000L);
      case 73:
         return jjMoveStringLiteralDfa15_0(active0, 0x2000000L);
      case 78:
         if ((active0 & 0x10000000L) != 0L)
            return jjStopAtPos(14, 28);
         break;
      default :
         break;
   }
   return jjStartNfa_0(13, active0);
}
static private int jjMoveStringLiteralDfa15_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(13, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0);
      return 15;
   }
   switch(curChar)
   {
      case 79:
         return jjMoveStringLiteralDfa16_0(active0, 0x2000000L);
      case 84:
         return jjMoveStringLiteralDfa16_0(active0, 0x20000L);
      default :
         break;
   }
   return jjStartNfa_0(14, active0);
}
static private int jjMoveStringLiteralDfa16_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(14, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, active0);
      return 16;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa17_0(active0, 0x20000L);
      case 78:
         return jjMoveStringLiteralDfa17_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(15, active0);
}
static private int jjMoveStringLiteralDfa17_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(15, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(16, active0);
      return 17;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa18_0(active0, 0x2000000L);
      case 79:
         return jjMoveStringLiteralDfa18_0(active0, 0x20000L);
      default :
         break;
   }
   return jjStartNfa_0(16, active0);
}
static private int jjMoveStringLiteralDfa18_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(16, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(17, active0);
      return 18;
   }
   switch(curChar)
   {
      case 78:
         if ((active0 & 0x20000L) != 0L)
            return jjStopAtPos(18, 17);
         break;
      case 83:
         return jjMoveStringLiteralDfa19_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(17, active0);
}
static private int jjMoveStringLiteralDfa19_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(17, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(18, active0);
      return 19;
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa20_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(18, active0);
}
static private int jjMoveStringLiteralDfa20_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(18, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(19, active0);
      return 20;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa21_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(19, active0);
}
static private int jjMoveStringLiteralDfa21_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(19, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(20, active0);
      return 21;
   }
   switch(curChar)
   {
      case 84:
         return jjMoveStringLiteralDfa22_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(20, active0);
}
static private int jjMoveStringLiteralDfa22_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(20, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(21, active0);
      return 22;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa23_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(21, active0);
}
static private int jjMoveStringLiteralDfa23_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(21, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(22, active0);
      return 23;
   }
   switch(curChar)
   {
      case 79:
         return jjMoveStringLiteralDfa24_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(22, active0);
}
static private int jjMoveStringLiteralDfa24_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(22, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(23, active0);
      return 24;
   }
   switch(curChar)
   {
      case 78:
         if ((active0 & 0x2000000L) != 0L)
            return jjStopAtPos(24, 25);
         break;
      default :
         break;
   }
   return jjStartNfa_0(23, active0);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 12;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000100000000L & l) != 0L)
                  {
                     if (kind > 13)
                        kind = 13;
                     jjCheckNAdd(2);
                  }
                  else if (curChar == 33)
                     jjstateSet[jjnewStateCnt++] = 3;
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 9)
                        kind = 9;
                     jjCheckNAddTwoStates(10, 11);
                  }
                  break;
               case 12:
                  if ((0x3ff000100000000L & l) != 0L)
                  {
                     if (kind > 13)
                        kind = 13;
                     jjCheckNAdd(2);
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 11)
                        kind = 11;
                     jjCheckNAdd(1);
                  }
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAdd(1);
                  break;
               case 2:
                  if ((0x3ff000100000000L & l) == 0L)
                     break;
                  if (kind > 13)
                     kind = 13;
                  jjCheckNAdd(2);
                  break;
               case 3:
                  if (curChar == 33)
                     jjCheckNAddStates(0, 2);
                  break;
               case 4:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 5:
                  if ((0x2400L & l) != 0L && kind > 14)
                     kind = 14;
                  break;
               case 6:
                  if (curChar == 10 && kind > 14)
                     kind = 14;
                  break;
               case 7:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if (curChar == 33)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 9:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAddTwoStates(10, 11);
                  break;
               case 10:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAdd(10);
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(11);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 13)
                        kind = 13;
                     jjCheckNAdd(2);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 11)
                        kind = 11;
                     jjCheckNAdd(1);
                  }
                  break;
               case 12:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 13)
                        kind = 13;
                     jjCheckNAdd(2);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 11)
                        kind = 11;
                     jjCheckNAdd(1);
                  }
                  break;
               case 1:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAdd(1);
                  break;
               case 2:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 13)
                     kind = 13;
                  jjCheckNAdd(2);
                  break;
               case 4:
                  jjAddStates(0, 2);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 4:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(0, 2);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 12 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   4, 5, 7, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, "\53", "\55", "\52", "\57", null, null, null, null, 
null, null, "\120\122\117\107\122\101\115", "\73", 
"\103\101\116\126\101\123\55\111\116\111\124\55\123\105\103\124\111\117\116", "\72", "\103\117\116\123\124", "\103\141\156\166\141\163\130", "\75", 
"\103\141\156\166\141\163\131", "\103\165\162\163\157\162\130", "\103\165\162\163\157\162\131", 
"\102\122\125\123\110\55\104\105\103\114\101\122\101\124\111\117\116\55\123\105\103\124\111\117\116", "\102\122\125\123\110", "\54", 
"\104\122\101\127\111\116\107\55\123\105\103\124\111\117\116", "\122\105\116\105\127\55\102\122\125\123\110", "\47", 
"\120\101\111\116\124\55\103\101\116\126\101\123", "\105\130\110\111\102\111\124\55\103\101\116\126\101\123", "\115\117\126\105", 
"\124\117", "\50", "\51", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x1fffffbbe1L, 
};
static final long[] jjtoSkip = {
   0x401eL, 
};
static final long[] jjtoSpecial = {
   0x4000L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[12];
static private final int[] jjstateSet = new int[24];
private static final StringBuilder jjimage = new StringBuilder();
private static StringBuilder image = jjimage;
private static int jjimageLen;
private static int lengthOfMatch;
static protected char curChar;
/** Constructor. */
public PeakassoTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public PeakassoTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 12; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   if (jjmatchedPos < 0)
   {
      if (image == null)
         curTokenImage = "";
      else
         curTokenImage = image.toString();
      beginLine = endLine = input_stream.getBeginLine();
      beginColumn = endColumn = input_stream.getBeginColumn();
   }
   else
   {
      String im = jjstrLiteralImages[jjmatchedKind];
      curTokenImage = (im == null) ? input_stream.GetImage() : im;
      beginLine = input_stream.getBeginLine();
      beginColumn = input_stream.getBeginColumn();
      endLine = input_stream.getEndLine();
      endColumn = input_stream.getEndColumn();
   }
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }
   image = jjimage;
   image.setLength(0);
   jjimageLen = 0;

   try { input_stream.backup(0);
      while (curChar <= 13 && (0x2600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 13;
   jjmatchedPos = -1;
   curPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         matchedToken.specialToken = specialToken;
         TokenLexicalActions(matchedToken);
         return matchedToken;
      }
      else
      {
         if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
         {
            matchedToken = jjFillToken();
            if (specialToken == null)
               specialToken = matchedToken;
            else
            {
               matchedToken.specialToken = specialToken;
               specialToken = (specialToken.next = matchedToken);
            }
         }
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static int[] jjemptyLineNo = new int[1];
static int[] jjemptyColNo = new int[1];
static boolean[] jjbeenHere = new boolean[1];
static void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 0 :
         break;
      case 5 :
         break;
      case 6 :
         break;
      case 7 :
         break;
      case 8 :
         break;
      case 9 :
         break;
      case 11 :
         break;
      case 12 :
         break;
      case 13 :
         if (jjmatchedPos == -1)
         {
            if (jjbeenHere[0] &&
                jjemptyLineNo[0] == input_stream.getBeginLine() &&
                jjemptyColNo[0] == input_stream.getBeginColumn())
               throw new TokenMgrError(("Error: Bailing out of infinite loop caused by repeated empty string matches at line " + input_stream.getBeginLine() + ", column " + input_stream.getBeginColumn() + "."), TokenMgrError.LOOP_DETECTED);
            jjemptyLineNo[0] = input_stream.getBeginLine();
            jjemptyColNo[0] = input_stream.getBeginColumn();
            jjbeenHere[0] = true;
         }
         break;
      case 15 :
         break;
      case 16 :
         break;
      case 17 :
         break;
      case 18 :
         break;
      case 19 :
         break;
      case 20 :
         break;
      case 21 :
         break;
      case 22 :
         break;
      case 23 :
         break;
      case 24 :
         break;
      case 25 :
         break;
      case 26 :
         break;
      case 27 :
         break;
      case 28 :
         break;
      case 29 :
         break;
      case 30 :
         break;
      case 31 :
         break;
      case 32 :
         break;
      case 33 :
         break;
      case 34 :
         break;
      case 35 :
         break;
      case 36 :
         break;
      default :
         break;
   }
}
static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
