/* Generated By:JavaCC: Do not edit this line. PeakassoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PeakassoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int CONSTANT = 9;
  /** RegularExpression Id. */
  int DIGIT = 10;
  /** RegularExpression Id. */
  int ID = 11;
  /** RegularExpression Id. */
  int int_lit = 12;
  /** RegularExpression Id. */
  int message = 13;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<CONSTANT>",
    "<DIGIT>",
    "<ID>",
    "<int_lit>",
    "<message>",
    "<SINGLE_LINE_COMMENT>",
    "\"PROGRAM\"",
    "\";\"",
    "\"CANVAS-INIT-SECTION\"",
    "\":\"",
    "\"CONST\"",
    "\"CanvasX\"",
    "\"=\"",
    "\"CanvasY\"",
    "\"CursorX\"",
    "\"CursorY\"",
    "\"BRUSH-DECLARATION-SECTION\"",
    "\"BRUSH\"",
    "\",\"",
    "\"DRAWING-SECTION\"",
    "\"RENEW-BRUSH\"",
    "\"\\\'\"",
    "\"PAINT-CANVAS\"",
    "\"EXHIBIT-CANVAS\"",
    "\"MOVE\"",
    "\"TO\"",
    "\"(\"",
    "\")\"",
  };

}
